-- Create student_presence table for tracking online students
CREATE TABLE IF NOT EXISTS public.student_presence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  class_id UUID NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
  is_online BOOLEAN DEFAULT false,
  last_seen TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(student_id, class_id)
);

-- Enable Row Level Security
ALTER TABLE public.student_presence ENABLE ROW LEVEL SECURITY;

-- RLS Policies (follow security best practices)
-- Note: Teachers are identified by being the teacher_id in the classes table
-- This subquery is efficient due to the index on classes(teacher_id)

-- Drop existing policies first (for re-running this migration)
DROP POLICY IF EXISTS "Teachers can view presence for their classes" ON public.student_presence;
DROP POLICY IF EXISTS "Students can update own presence" ON public.student_presence;
DROP POLICY IF EXISTS "Students can insert own presence" ON public.student_presence;
DROP POLICY IF EXISTS "Students can view own presence" ON public.student_presence;

-- Teachers can see presence for their classes
CREATE POLICY "Teachers can view presence for their classes"
  ON public.student_presence FOR SELECT
  TO authenticated
  USING (
    class_id IN (
      SELECT id FROM public.classes WHERE teacher_id = auth.uid()
    )
  );

-- Students can update their own presence
CREATE POLICY "Students can update own presence"
  ON public.student_presence FOR UPDATE
  TO authenticated
  USING (student_id = auth.uid())
  WITH CHECK (student_id = auth.uid());

-- Students can insert their own presence
CREATE POLICY "Students can insert own presence"
  ON public.student_presence FOR INSERT
  TO authenticated
  WITH CHECK (student_id = auth.uid());

-- Students can view their own presence
CREATE POLICY "Students can view own presence"
  ON public.student_presence FOR SELECT
  TO authenticated
  USING (student_id = auth.uid());

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_student_presence_class_online
  ON public.student_presence(class_id, is_online, last_seen DESC);

CREATE INDEX IF NOT EXISTS idx_student_presence_student
  ON public.student_presence(student_id);

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_student_presence_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS student_presence_updated_at ON public.student_presence;
CREATE TRIGGER student_presence_updated_at
  BEFORE UPDATE ON public.student_presence
  FOR EACH ROW
  EXECUTE FUNCTION update_student_presence_updated_at();

-- Function to clean up old offline presence records (optional, can be run periodically)
CREATE OR REPLACE FUNCTION cleanup_old_presence()
RETURNS void AS $$
BEGIN
  DELETE FROM public.student_presence
  WHERE is_online = false
    AND updated_at < NOW() - INTERVAL '7 days';
END;
$$ LANGUAGE plpgsql;
